// Copyright (c) 2026 Jonathan Belson
// Licensed under the MIT License — use freely, keep this notice.
// SPDX-License-Identifier: MIT
// Full terms: see LICENSE in the project root.

module;

#include <cstdint>

export module unicode.script;

import std;

namespace unicode::script
{
	using Utf32Text = std::vector<uint32_t>;

	export enum class Script
	{
		Unknown,

		Adlam, 
		Ahom, 
		AnatolianHieroglyphs, 
		Arabic, 
		Armenian, 
		Avestan, 
		Balinese, 
		Bamum, 
		BassaVah, 
		Batak, 
		Bengali, 
		Bhaiksuki, 
		Bopomofo, 
		Brahmi, 
		Braille, 
		Buginese, 
		Buhid, 
		CanadianAboriginal, 
		Carian, 
		CaucasianAlbanian, 
		Chakma, 
		Cham, 
		Cherokee, 
		Chorasmian, 
		Common, 
		Coptic, 
		Cuneiform, 
		Cypriot, 
		CyproMinoan, 
		Cyrillic, 
		Deseret, 
		Devanagari, 
		DivesAkuru, 
		Dogra, 
		Duployan, 
		EgyptianHieroglyphs, 
		Elbasan, 
		Elymaic, 
		Ethiopic, 
		Garay, 
		Georgian, 
		Glagolitic, 
		Gothic, 
		Grantha, 
		Greek, 
		Gujarati, 
		GunjalaGondi, 
		Gurmukhi, 
		GurungKhema, 
		Han, 
		Hangul, 
		HanifiRohingya, 
		Hanunoo, 
		Hatran, 
		Hebrew, 
		Hiragana, 
		ImperialAramaic, 
		Inherited, 
		InscriptionalPahlavi, 
		InscriptionalParthian, 
		Javanese, 
		Kaithi, 
		Kannada, 
		Katakana, 
		Kawi, 
		KayahLi, 
		Kharoshthi, 
		KhitanSmallScript, 
		Khmer, 
		Khojki, 
		Khudawadi, 
		KiratRai, 
		Lao, 
		Latin, 
		Lepcha, 
		Limbu, 
		LinearA, 
		LinearB, 
		Lisu, 
		Lycian, 
		Lydian, 
		Mahajani, 
		Makasar, 
		Malayalam, 
		Mandaic, 
		Manichaean, 
		Marchen, 
		MasaramGondi, 
		Medefaidrin, 
		MeeteiMayek, 
		MendeKikakui, 
		MeroiticCursive, 
		MeroiticHieroglyphs, 
		Miao, 
		Modi, 
		Mongolian, 
		Mro, 
		Multani, 
		Myanmar, 
		Nabataean, 
		NagMundari, 
		Nandinagari, 
		NewTaiLue, 
		Newa, 
		Nko, 
		Nushu, 
		NyiakengPuachueHmong, 
		Ogham, 
		OlChiki, 
		OlOnal, 
		OldHungarian, 
		OldItalic, 
		OldNorthArabian, 
		OldPermic, 
		OldPersian, 
		OldSogdian, 
		OldSouthArabian, 
		OldTurkic, 
		OldUyghur, 
		Oriya, 
		Osage, 
		Osmanya, 
		PahawhHmong, 
		Palmyrene, 
		PauCinHau, 
		PhagsPa, 
		Phoenician, 
		PsalterPahlavi, 
		Rejang, 
		Runic, 
		Samaritan, 
		Saurashtra, 
		Sharada, 
		Shavian, 
		Siddham, 
		SignWriting, 
		Sinhala, 
		Sogdian, 
		SoraSompeng, 
		Soyombo, 
		Sundanese, 
		Sunuwar, 
		SylotiNagri, 
		Syriac, 
		Tagalog, 
		Tagbanwa, 
		TaiLe, 
		TaiTham, 
		TaiViet, 
		Takri, 
		Tamil, 
		Tangsa, 
		Tangut, 
		Telugu, 
		Thaana, 
		Thai, 
		Tibetan, 
		Tifinagh, 
		Tirhuta, 
		Todhri, 
		Toto, 
		TuluTigalari, 
		Ugaritic, 
		Vai, 
		Vithkuqi, 
		Wancho, 
		WarangCiti, 
		Yezidi, 
		Yi, 
		ZanabazarSquare, 
	};

	// Find script of specified character.
	export Script GetScript(uint32_t codePoint);

	//export bool IsLeftToRight(uint32_t codePoint);
	//export bool IsLeftToRight(const Utf32Text& utf32);

	//export bool IsShaped(uint32_t codePoint);
	//export bool IsShaped(const Utf32Text& utf32);

	//// Using 'simple' to mean left to right, not shaped, not a mark.
	//export bool IsSimple(uint32_t codePoint);
	//export bool IsSimple(const Utf32Text& utf32);
};
