// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vector_tile.proto
// Protobuf C++ Version: 5.29.5

#include "vector_tile.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace vector_tile {

inline constexpr Tile_Value::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        string_value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        double_value_{0},
        int_value_{::int64_t{0}},
        float_value_{0},
        bool_value_{false},
        uint_value_{::uint64_t{0u}},
        sint_value_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR Tile_Value::Tile_Value(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct Tile_ValueDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Tile_ValueDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Tile_ValueDefaultTypeInternal() {}
  union {
    Tile_Value _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Tile_ValueDefaultTypeInternal _Tile_Value_default_instance_;

inline constexpr Tile_Feature::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        tags_{},
        _tags_cached_byte_size_{0},
        geometry_{},
        _geometry_cached_byte_size_{0},
        id_{::uint64_t{0u}},
        type_{static_cast< ::vector_tile::Tile_GeomType >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR Tile_Feature::Tile_Feature(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct Tile_FeatureDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Tile_FeatureDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Tile_FeatureDefaultTypeInternal() {}
  union {
    Tile_Feature _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Tile_FeatureDefaultTypeInternal _Tile_Feature_default_instance_;

inline constexpr Tile_Layer::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        features_{},
        keys_{},
        values_{},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        extent_{4096u},
        version_{1u} {}

template <typename>
PROTOBUF_CONSTEXPR Tile_Layer::Tile_Layer(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct Tile_LayerDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Tile_LayerDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Tile_LayerDefaultTypeInternal() {}
  union {
    Tile_Layer _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Tile_LayerDefaultTypeInternal _Tile_Layer_default_instance_;

inline constexpr Tile::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : layers_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Tile::Tile(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TileDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TileDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TileDefaultTypeInternal() {}
  union {
    Tile _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TileDefaultTypeInternal _Tile_default_instance_;
}  // namespace vector_tile
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_vector_5ftile_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_vector_5ftile_2eproto = nullptr;
const ::uint32_t
    TableStruct_vector_5ftile_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::vector_tile::Tile_Value, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::vector_tile::Tile_Value, _internal_metadata_),
        PROTOBUF_FIELD_OFFSET(::vector_tile::Tile_Value, _impl_._extensions_),
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::vector_tile::Tile_Value, _impl_.string_value_),
        PROTOBUF_FIELD_OFFSET(::vector_tile::Tile_Value, _impl_.float_value_),
        PROTOBUF_FIELD_OFFSET(::vector_tile::Tile_Value, _impl_.double_value_),
        PROTOBUF_FIELD_OFFSET(::vector_tile::Tile_Value, _impl_.int_value_),
        PROTOBUF_FIELD_OFFSET(::vector_tile::Tile_Value, _impl_.uint_value_),
        PROTOBUF_FIELD_OFFSET(::vector_tile::Tile_Value, _impl_.sint_value_),
        PROTOBUF_FIELD_OFFSET(::vector_tile::Tile_Value, _impl_.bool_value_),
        0,
        3,
        1,
        2,
        5,
        6,
        4,
        PROTOBUF_FIELD_OFFSET(::vector_tile::Tile_Feature, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::vector_tile::Tile_Feature, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::vector_tile::Tile_Feature, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::vector_tile::Tile_Feature, _impl_.tags_),
        PROTOBUF_FIELD_OFFSET(::vector_tile::Tile_Feature, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::vector_tile::Tile_Feature, _impl_.geometry_),
        0,
        ~0u,
        1,
        ~0u,
        PROTOBUF_FIELD_OFFSET(::vector_tile::Tile_Layer, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::vector_tile::Tile_Layer, _internal_metadata_),
        PROTOBUF_FIELD_OFFSET(::vector_tile::Tile_Layer, _impl_._extensions_),
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::vector_tile::Tile_Layer, _impl_.version_),
        PROTOBUF_FIELD_OFFSET(::vector_tile::Tile_Layer, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::vector_tile::Tile_Layer, _impl_.features_),
        PROTOBUF_FIELD_OFFSET(::vector_tile::Tile_Layer, _impl_.keys_),
        PROTOBUF_FIELD_OFFSET(::vector_tile::Tile_Layer, _impl_.values_),
        PROTOBUF_FIELD_OFFSET(::vector_tile::Tile_Layer, _impl_.extent_),
        2,
        0,
        ~0u,
        ~0u,
        ~0u,
        1,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::vector_tile::Tile, _internal_metadata_),
        PROTOBUF_FIELD_OFFSET(::vector_tile::Tile, _impl_._extensions_),
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::vector_tile::Tile, _impl_.layers_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 15, -1, sizeof(::vector_tile::Tile_Value)},
        {22, 34, -1, sizeof(::vector_tile::Tile_Feature)},
        {38, 52, -1, sizeof(::vector_tile::Tile_Layer)},
        {58, -1, -1, sizeof(::vector_tile::Tile)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::vector_tile::_Tile_Value_default_instance_._instance,
    &::vector_tile::_Tile_Feature_default_instance_._instance,
    &::vector_tile::_Tile_Layer_default_instance_._instance,
    &::vector_tile::_Tile_default_instance_._instance,
};
const char descriptor_table_protodef_vector_5ftile_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021vector_tile.proto\022\013vector_tile\"\300\004\n\004Til"
    "e\022\'\n\006layers\030\003 \003(\0132\027.vector_tile.Tile.Lay"
    "er\032\241\001\n\005Value\022\024\n\014string_value\030\001 \001(\t\022\023\n\013fl"
    "oat_value\030\002 \001(\002\022\024\n\014double_value\030\003 \001(\001\022\021\n"
    "\tint_value\030\004 \001(\003\022\022\n\nuint_value\030\005 \001(\004\022\022\n\n"
    "sint_value\030\006 \001(\022\022\022\n\nbool_value\030\007 \001(\010*\010\010\010"
    "\020\200\200\200\200\002\032s\n\007Feature\022\r\n\002id\030\001 \001(\004:\0010\022\020\n\004tags"
    "\030\002 \003(\rB\002\020\001\0221\n\004type\030\003 \001(\0162\032.vector_tile.T"
    "ile.GeomType:\007UNKNOWN\022\024\n\010geometry\030\004 \003(\rB"
    "\002\020\001\032\255\001\n\005Layer\022\022\n\007version\030\017 \002(\r:\0011\022\014\n\004nam"
    "e\030\001 \002(\t\022+\n\010features\030\002 \003(\0132\031.vector_tile."
    "Tile.Feature\022\014\n\004keys\030\003 \003(\t\022\'\n\006values\030\004 \003"
    "(\0132\027.vector_tile.Tile.Value\022\024\n\006extent\030\005 "
    "\001(\r:\0044096*\010\010\020\020\200\200\200\200\002\"\?\n\010GeomType\022\013\n\007UNKNO"
    "WN\020\000\022\t\n\005POINT\020\001\022\016\n\nLINESTRING\020\002\022\013\n\007POLYG"
    "ON\020\003*\005\010\020\020\200@"
};
static ::absl::once_flag descriptor_table_vector_5ftile_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_vector_5ftile_2eproto = {
    false,
    false,
    611,
    descriptor_table_protodef_vector_5ftile_2eproto,
    "vector_tile.proto",
    &descriptor_table_vector_5ftile_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_vector_5ftile_2eproto::offsets,
    file_level_enum_descriptors_vector_5ftile_2eproto,
    file_level_service_descriptors_vector_5ftile_2eproto,
};
namespace vector_tile {
const ::google::protobuf::EnumDescriptor* Tile_GeomType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_vector_5ftile_2eproto);
  return file_level_enum_descriptors_vector_5ftile_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Tile_GeomType_internal_data_[] = {
    262144u, 0u, };
bool Tile_GeomType_IsValid(int value) {
  return 0 <= value && value <= 3;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr Tile_GeomType Tile::UNKNOWN;
constexpr Tile_GeomType Tile::POINT;
constexpr Tile_GeomType Tile::LINESTRING;
constexpr Tile_GeomType Tile::POLYGON;
constexpr Tile_GeomType Tile::GeomType_MIN;
constexpr Tile_GeomType Tile::GeomType_MAX;
constexpr int Tile::GeomType_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class Tile_Value::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Tile_Value>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_._has_bits_);
};

Tile_Value::Tile_Value(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:vector_tile.Tile.Value)
}
inline PROTOBUF_NDEBUG_INLINE Tile_Value::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::vector_tile::Tile_Value& from_msg)
      : _extensions_{visibility, arena},
        _has_bits_{from._has_bits_},
        _cached_size_{0},
        string_value_(arena, from.string_value_) {}

Tile_Value::Tile_Value(
    ::google::protobuf::Arena* arena,
    const Tile_Value& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Tile_Value* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_._extensions_.MergeFrom(this, from._impl_._extensions_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, double_value_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, double_value_),
           offsetof(Impl_, sint_value_) -
               offsetof(Impl_, double_value_) +
               sizeof(Impl_::sint_value_));

  // @@protoc_insertion_point(copy_constructor:vector_tile.Tile.Value)
}
inline PROTOBUF_NDEBUG_INLINE Tile_Value::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _extensions_{visibility, arena},
        _cached_size_{0},
        string_value_(arena) {}

inline void Tile_Value::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, double_value_),
           0,
           offsetof(Impl_, sint_value_) -
               offsetof(Impl_, double_value_) +
               sizeof(Impl_::sint_value_));
}
Tile_Value::~Tile_Value() {
  // @@protoc_insertion_point(destructor:vector_tile.Tile.Value)
  SharedDtor(*this);
}
inline void Tile_Value::SharedDtor(MessageLite& self) {
  Tile_Value& this_ = static_cast<Tile_Value&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.string_value_.Destroy();
  this_._impl_.~Impl_();
}

inline void* Tile_Value::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Tile_Value(arena);
}
constexpr auto Tile_Value::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_._extensions_) +
          decltype(Tile_Value::_impl_._extensions_)::InternalGetArenaOffset(
              ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(Tile_Value), alignof(Tile_Value), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Tile_Value::PlacementNew_,
                                 sizeof(Tile_Value),
                                 alignof(Tile_Value));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Tile_Value::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Tile_Value_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        Tile_Value::IsInitializedImpl,
        &Tile_Value::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Tile_Value>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Tile_Value::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Tile_Value>(), &Tile_Value::ByteSizeLong,
            &Tile_Value::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_._cached_size_),
        false,
    },
    &Tile_Value::kDescriptorMethods,
    &descriptor_table_vector_5ftile_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Tile_Value::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 0, 43, 2> Tile_Value::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_._extensions_),
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::vector_tile::Tile_Value>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional string string_value = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.string_value_)}},
    // optional float float_value = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 3, 0, PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.float_value_)}},
    // optional double double_value = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 1, 0, PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.double_value_)}},
    // optional int64 int_value = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Tile_Value, _impl_.int_value_), 2>(),
     {32, 2, 0, PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.int_value_)}},
    // optional uint64 uint_value = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Tile_Value, _impl_.uint_value_), 5>(),
     {40, 5, 0, PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.uint_value_)}},
    // optional sint64 sint_value = 6;
    {::_pbi::TcParser::FastZ64S1,
     {48, 6, 0, PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.sint_value_)}},
    // optional bool bool_value = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Tile_Value, _impl_.bool_value_), 4>(),
     {56, 4, 0, PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.bool_value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string string_value = 1;
    {PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.string_value_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional float float_value = 2;
    {PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.float_value_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional double double_value = 3;
    {PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.double_value_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // optional int64 int_value = 4;
    {PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.int_value_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional uint64 uint_value = 5;
    {PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.uint_value_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // optional sint64 sint_value = 6;
    {PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.sint_value_), _Internal::kHasBitsOffset + 6, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kSInt64)},
    // optional bool bool_value = 7;
    {PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.bool_value_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\26\14\0\0\0\0\0\0"
    "vector_tile.Tile.Value"
    "string_value"
  }},
};

PROTOBUF_NOINLINE void Tile_Value::Clear() {
// @@protoc_insertion_point(message_clear_start:vector_tile.Tile.Value)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_._extensions_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.string_value_.ClearNonDefaultToEmpty();
  }
  if (cached_has_bits & 0x0000007eu) {
    ::memset(&_impl_.double_value_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.sint_value_) -
        reinterpret_cast<char*>(&_impl_.double_value_)) + sizeof(_impl_.sint_value_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Tile_Value::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Tile_Value& this_ = static_cast<const Tile_Value&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Tile_Value::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Tile_Value& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:vector_tile.Tile.Value)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional string string_value = 1;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_string_value();
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                        "vector_tile.Tile.Value.string_value");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // optional float float_value = 2;
          if (cached_has_bits & 0x00000008u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                2, this_._internal_float_value(), target);
          }

          // optional double double_value = 3;
          if (cached_has_bits & 0x00000002u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                3, this_._internal_double_value(), target);
          }

          // optional int64 int_value = 4;
          if (cached_has_bits & 0x00000004u) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<4>(
                    stream, this_._internal_int_value(), target);
          }

          // optional uint64 uint_value = 5;
          if (cached_has_bits & 0x00000020u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                5, this_._internal_uint_value(), target);
          }

          // optional sint64 sint_value = 6;
          if (cached_has_bits & 0x00000040u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteSInt64ToArray(
                6, this_._internal_sint_value(), target);
          }

          // optional bool bool_value = 7;
          if (cached_has_bits & 0x00000010u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                7, this_._internal_bool_value(), target);
          }

          // Extension range [8, 536870912)
          target = this_._impl_._extensions_._InternalSerialize(
              internal_default_instance(), 8, 536870912, target, stream);
          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:vector_tile.Tile.Value)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Tile_Value::ByteSizeLong(const MessageLite& base) {
          const Tile_Value& this_ = static_cast<const Tile_Value&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Tile_Value::ByteSizeLong() const {
          const Tile_Value& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:vector_tile.Tile.Value)
          ::size_t total_size = 0;
          total_size += this_._impl_._extensions_.ByteSize();

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x0000007fu) {
            // optional string string_value = 1;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_string_value());
            }
            // optional double double_value = 3;
            if (cached_has_bits & 0x00000002u) {
              total_size += 9;
            }
            // optional int64 int_value = 4;
            if (cached_has_bits & 0x00000004u) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_int_value());
            }
            // optional float float_value = 2;
            if (cached_has_bits & 0x00000008u) {
              total_size += 5;
            }
            // optional bool bool_value = 7;
            if (cached_has_bits & 0x00000010u) {
              total_size += 2;
            }
            // optional uint64 uint_value = 5;
            if (cached_has_bits & 0x00000020u) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_uint_value());
            }
            // optional sint64 sint_value = 6;
            if (cached_has_bits & 0x00000040u) {
              total_size += ::_pbi::WireFormatLite::SInt64SizePlusOne(
                  this_._internal_sint_value());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Tile_Value::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Tile_Value*>(&to_msg);
  auto& from = static_cast<const Tile_Value&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:vector_tile.Tile.Value)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000007fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_string_value(from._internal_string_value());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.double_value_ = from._impl_.double_value_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.int_value_ = from._impl_.int_value_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.float_value_ = from._impl_.float_value_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.bool_value_ = from._impl_.bool_value_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.uint_value_ = from._impl_.uint_value_;
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_impl_.sint_value_ = from._impl_.sint_value_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_impl_._extensions_.MergeFrom(internal_default_instance(), from._impl_._extensions_);
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Tile_Value::CopyFrom(const Tile_Value& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:vector_tile.Tile.Value)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Tile_Value::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const Tile_Value&>(msg);
  if (!this_._impl_._extensions_.IsInitialized(
          internal_default_instance())) {
    return false;
  }
  return true;
}

void Tile_Value::InternalSwap(Tile_Value* PROTOBUF_RESTRICT other) {
  using std::swap;
  _impl_._extensions_.InternalSwap(&other->_impl_._extensions_);
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.string_value_, &other->_impl_.string_value_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.sint_value_)
      + sizeof(Tile_Value::_impl_.sint_value_)
      - PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.double_value_)>(
          reinterpret_cast<char*>(&_impl_.double_value_),
          reinterpret_cast<char*>(&other->_impl_.double_value_));
}

::google::protobuf::Metadata Tile_Value::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Tile_Feature::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Tile_Feature>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Tile_Feature, _impl_._has_bits_);
};

Tile_Feature::Tile_Feature(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:vector_tile.Tile.Feature)
}
inline PROTOBUF_NDEBUG_INLINE Tile_Feature::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::vector_tile::Tile_Feature& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        tags_{visibility, arena, from.tags_},
        _tags_cached_byte_size_{0},
        geometry_{visibility, arena, from.geometry_},
        _geometry_cached_byte_size_{0} {}

Tile_Feature::Tile_Feature(
    ::google::protobuf::Arena* arena,
    const Tile_Feature& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Tile_Feature* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, type_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::type_));

  // @@protoc_insertion_point(copy_constructor:vector_tile.Tile.Feature)
}
inline PROTOBUF_NDEBUG_INLINE Tile_Feature::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        tags_{visibility, arena},
        _tags_cached_byte_size_{0},
        geometry_{visibility, arena},
        _geometry_cached_byte_size_{0} {}

inline void Tile_Feature::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, type_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::type_));
}
Tile_Feature::~Tile_Feature() {
  // @@protoc_insertion_point(destructor:vector_tile.Tile.Feature)
  SharedDtor(*this);
}
inline void Tile_Feature::SharedDtor(MessageLite& self) {
  Tile_Feature& this_ = static_cast<Tile_Feature&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* Tile_Feature::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Tile_Feature(arena);
}
constexpr auto Tile_Feature::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Tile_Feature, _impl_.tags_) +
          decltype(Tile_Feature::_impl_.tags_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(Tile_Feature, _impl_.geometry_) +
          decltype(Tile_Feature::_impl_.geometry_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(Tile_Feature), alignof(Tile_Feature), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Tile_Feature::PlacementNew_,
                                 sizeof(Tile_Feature),
                                 alignof(Tile_Feature));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Tile_Feature::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Tile_Feature_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Tile_Feature::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Tile_Feature>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Tile_Feature::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Tile_Feature>(), &Tile_Feature::ByteSizeLong,
            &Tile_Feature::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Tile_Feature, _impl_._cached_size_),
        false,
    },
    &Tile_Feature::kDescriptorMethods,
    &descriptor_table_vector_5ftile_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Tile_Feature::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 0, 2> Tile_Feature::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Tile_Feature, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::vector_tile::Tile_Feature>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated uint32 geometry = 4 [packed = true];
    {::_pbi::TcParser::FastV32P1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(Tile_Feature, _impl_.geometry_)}},
    // optional uint64 id = 1 [default = 0];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Tile_Feature, _impl_.id_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(Tile_Feature, _impl_.id_)}},
    // repeated uint32 tags = 2 [packed = true];
    {::_pbi::TcParser::FastV32P1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Tile_Feature, _impl_.tags_)}},
    // optional .vector_tile.Tile.GeomType type = 3 [default = UNKNOWN];
    {::_pbi::TcParser::FastEr0S1,
     {24, 1, 3, PROTOBUF_FIELD_OFFSET(Tile_Feature, _impl_.type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional uint64 id = 1 [default = 0];
    {PROTOBUF_FIELD_OFFSET(Tile_Feature, _impl_.id_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // repeated uint32 tags = 2 [packed = true];
    {PROTOBUF_FIELD_OFFSET(Tile_Feature, _impl_.tags_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt32)},
    // optional .vector_tile.Tile.GeomType type = 3 [default = UNKNOWN];
    {PROTOBUF_FIELD_OFFSET(Tile_Feature, _impl_.type_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
    // repeated uint32 geometry = 4 [packed = true];
    {PROTOBUF_FIELD_OFFSET(Tile_Feature, _impl_.geometry_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt32)},
  }}, {{
    {0, 4},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void Tile_Feature::Clear() {
// @@protoc_insertion_point(message_clear_start:vector_tile.Tile.Feature)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.tags_.Clear();
  _impl_.geometry_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    ::memset(&_impl_.id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.type_) -
        reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.type_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Tile_Feature::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Tile_Feature& this_ = static_cast<const Tile_Feature&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Tile_Feature::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Tile_Feature& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:vector_tile.Tile.Feature)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional uint64 id = 1 [default = 0];
          if (cached_has_bits & 0x00000001u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                1, this_._internal_id(), target);
          }

          // repeated uint32 tags = 2 [packed = true];
          {
            int byte_size = this_._impl_._tags_cached_byte_size_.Get();
            if (byte_size > 0) {
              target = stream->WriteUInt32Packed(
                  2, this_._internal_tags(), byte_size, target);
            }
          }

          // optional .vector_tile.Tile.GeomType type = 3 [default = UNKNOWN];
          if (cached_has_bits & 0x00000002u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                3, this_._internal_type(), target);
          }

          // repeated uint32 geometry = 4 [packed = true];
          {
            int byte_size = this_._impl_._geometry_cached_byte_size_.Get();
            if (byte_size > 0) {
              target = stream->WriteUInt32Packed(
                  4, this_._internal_geometry(), byte_size, target);
            }
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:vector_tile.Tile.Feature)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Tile_Feature::ByteSizeLong(const MessageLite& base) {
          const Tile_Feature& this_ = static_cast<const Tile_Feature&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Tile_Feature::ByteSizeLong() const {
          const Tile_Feature& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:vector_tile.Tile.Feature)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated uint32 tags = 2 [packed = true];
            {
              total_size +=
                  ::_pbi::WireFormatLite::UInt32SizeWithPackedTagSize(
                      this_._internal_tags(), 1,
                      this_._impl_._tags_cached_byte_size_);
            }
            // repeated uint32 geometry = 4 [packed = true];
            {
              total_size +=
                  ::_pbi::WireFormatLite::UInt32SizeWithPackedTagSize(
                      this_._internal_geometry(), 1,
                      this_._impl_._geometry_cached_byte_size_);
            }
          }
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // optional uint64 id = 1 [default = 0];
            if (cached_has_bits & 0x00000001u) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_id());
            }
            // optional .vector_tile.Tile.GeomType type = 3 [default = UNKNOWN];
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Tile_Feature::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Tile_Feature*>(&to_msg);
  auto& from = static_cast<const Tile_Feature&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:vector_tile.Tile.Feature)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_tags()->MergeFrom(from._internal_tags());
  _this->_internal_mutable_geometry()->MergeFrom(from._internal_geometry());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.id_ = from._impl_.id_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.type_ = from._impl_.type_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Tile_Feature::CopyFrom(const Tile_Feature& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:vector_tile.Tile.Feature)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Tile_Feature::InternalSwap(Tile_Feature* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.tags_.InternalSwap(&other->_impl_.tags_);
  _impl_.geometry_.InternalSwap(&other->_impl_.geometry_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Tile_Feature, _impl_.type_)
      + sizeof(Tile_Feature::_impl_.type_)
      - PROTOBUF_FIELD_OFFSET(Tile_Feature, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata Tile_Feature::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Tile_Layer::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Tile_Layer>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000005) ^ 0x00000005) != 0;
  }
};

Tile_Layer::Tile_Layer(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:vector_tile.Tile.Layer)
}
inline PROTOBUF_NDEBUG_INLINE Tile_Layer::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::vector_tile::Tile_Layer& from_msg)
      : _extensions_{visibility, arena},
        _has_bits_{from._has_bits_},
        _cached_size_{0},
        features_{visibility, arena, from.features_},
        keys_{visibility, arena, from.keys_},
        values_{visibility, arena, from.values_},
        name_(arena, from.name_) {}

Tile_Layer::Tile_Layer(
    ::google::protobuf::Arena* arena,
    const Tile_Layer& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Tile_Layer* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_._extensions_.MergeFrom(this, from._impl_._extensions_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, extent_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, extent_),
           offsetof(Impl_, version_) -
               offsetof(Impl_, extent_) +
               sizeof(Impl_::version_));

  // @@protoc_insertion_point(copy_constructor:vector_tile.Tile.Layer)
}
inline PROTOBUF_NDEBUG_INLINE Tile_Layer::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _extensions_{visibility, arena},
        _cached_size_{0},
        features_{visibility, arena},
        keys_{visibility, arena},
        values_{visibility, arena},
        name_(arena),
        extent_{4096u},
        version_{1u} {}

inline void Tile_Layer::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Tile_Layer::~Tile_Layer() {
  // @@protoc_insertion_point(destructor:vector_tile.Tile.Layer)
  SharedDtor(*this);
}
inline void Tile_Layer::SharedDtor(MessageLite& self) {
  Tile_Layer& this_ = static_cast<Tile_Layer&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* Tile_Layer::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Tile_Layer(arena);
}
constexpr auto Tile_Layer::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_._extensions_) +
          decltype(Tile_Layer::_impl_._extensions_)::InternalGetArenaOffset(
              ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.features_) +
          decltype(Tile_Layer::_impl_.features_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.keys_) +
          decltype(Tile_Layer::_impl_.keys_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.values_) +
          decltype(Tile_Layer::_impl_.values_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(Tile_Layer), alignof(Tile_Layer), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Tile_Layer::PlacementNew_,
                                 sizeof(Tile_Layer),
                                 alignof(Tile_Layer));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Tile_Layer::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Tile_Layer_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        Tile_Layer::IsInitializedImpl,
        &Tile_Layer::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Tile_Layer>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Tile_Layer::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Tile_Layer>(), &Tile_Layer::ByteSizeLong,
            &Tile_Layer::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_._cached_size_),
        false,
    },
    &Tile_Layer::kDescriptorMethods,
    &descriptor_table_vector_5ftile_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Tile_Layer::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 2, 39, 2> Tile_Layer::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_._extensions_),
    15, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294950880,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::vector_tile::Tile_Layer>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // required string name = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.name_)}},
    // repeated .vector_tile.Tile.Feature features = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.features_)}},
    // repeated string keys = 3;
    {::_pbi::TcParser::FastSR1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.keys_)}},
    // repeated .vector_tile.Tile.Value values = 4;
    {::_pbi::TcParser::FastMtR1,
     {34, 63, 1, PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.values_)}},
    // optional uint32 extent = 5 [default = 4096];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Tile_Layer, _impl_.extent_), 1>(),
     {40, 1, 0, PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.extent_)}},
    {::_pbi::TcParser::MiniParse, {}},
    // required uint32 version = 15 [default = 1];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Tile_Layer, _impl_.version_), 2>(),
     {120, 2, 0, PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.version_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required string name = 1;
    {PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.name_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // repeated .vector_tile.Tile.Feature features = 2;
    {PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.features_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated string keys = 3;
    {PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.keys_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kRawString | ::_fl::kRepSString)},
    // repeated .vector_tile.Tile.Value values = 4;
    {PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.values_), -1, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional uint32 extent = 5 [default = 4096];
    {PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.extent_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // required uint32 version = 15 [default = 1];
    {PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.version_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }}, {{
    {::_pbi::TcParser::GetTable<::vector_tile::Tile_Feature>()},
    {::_pbi::TcParser::GetTable<::vector_tile::Tile_Value>()},
  }}, {{
    "\26\4\0\4\0\0\0\0"
    "vector_tile.Tile.Layer"
    "name"
    "keys"
  }},
};

PROTOBUF_NOINLINE void Tile_Layer::Clear() {
// @@protoc_insertion_point(message_clear_start:vector_tile.Tile.Layer)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_._extensions_.Clear();
  _impl_.features_.Clear();
  _impl_.keys_.Clear();
  _impl_.values_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.name_.ClearNonDefaultToEmpty();
    }
    _impl_.extent_ = 4096u;
    _impl_.version_ = 1u;
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Tile_Layer::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Tile_Layer& this_ = static_cast<const Tile_Layer&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Tile_Layer::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Tile_Layer& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:vector_tile.Tile.Layer)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // required string name = 1;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_name();
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                        "vector_tile.Tile.Layer.name");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // repeated .vector_tile.Tile.Feature features = 2;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_features_size());
               i < n; i++) {
            const auto& repfield = this_._internal_features().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    2, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // repeated string keys = 3;
          for (int i = 0, n = this_._internal_keys_size(); i < n; ++i) {
            const auto& s = this_._internal_keys().Get(i);
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                        "vector_tile.Tile.Layer.keys");
            target = stream->WriteString(3, s, target);
          }

          // repeated .vector_tile.Tile.Value values = 4;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_values_size());
               i < n; i++) {
            const auto& repfield = this_._internal_values().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    4, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // optional uint32 extent = 5 [default = 4096];
          if (cached_has_bits & 0x00000002u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                5, this_._internal_extent(), target);
          }

          // required uint32 version = 15 [default = 1];
          if (cached_has_bits & 0x00000004u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                15, this_._internal_version(), target);
          }

          // Extension range [16, 536870912)
          target = this_._impl_._extensions_._InternalSerialize(
              internal_default_instance(), 16, 536870912, target, stream);
          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:vector_tile.Tile.Layer)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Tile_Layer::ByteSizeLong(const MessageLite& base) {
          const Tile_Layer& this_ = static_cast<const Tile_Layer&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Tile_Layer::ByteSizeLong() const {
          const Tile_Layer& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:vector_tile.Tile.Layer)
          ::size_t total_size = 0;
          total_size += this_._impl_._extensions_.ByteSize();

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .vector_tile.Tile.Feature features = 2;
            {
              total_size += 1UL * this_._internal_features_size();
              for (const auto& msg : this_._internal_features()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
            // repeated string keys = 3;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_keys().size());
              for (int i = 0, n = this_._internal_keys().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
                    this_._internal_keys().Get(i));
              }
            }
            // repeated .vector_tile.Tile.Value values = 4;
            {
              total_size += 1UL * this_._internal_values_size();
              for (const auto& msg : this_._internal_values()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // required string name = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_name());
            }
          }
           {
            // optional uint32 extent = 5 [default = 4096];
            if (cached_has_bits & 0x00000002u) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_extent());
            }
          }
           {
            // required uint32 version = 15 [default = 1];
            if (cached_has_bits & 0x00000004u) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_version());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Tile_Layer::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Tile_Layer*>(&to_msg);
  auto& from = static_cast<const Tile_Layer&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:vector_tile.Tile.Layer)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_features()->MergeFrom(
      from._internal_features());
  _this->_internal_mutable_keys()->MergeFrom(from._internal_keys());
  _this->_internal_mutable_values()->MergeFrom(
      from._internal_values());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_name(from._internal_name());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.extent_ = from._impl_.extent_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.version_ = from._impl_.version_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_impl_._extensions_.MergeFrom(internal_default_instance(), from._impl_._extensions_);
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Tile_Layer::CopyFrom(const Tile_Layer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:vector_tile.Tile.Layer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Tile_Layer::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const Tile_Layer&>(msg);
  if (!this_._impl_._extensions_.IsInitialized(
          internal_default_instance())) {
    return false;
  }
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  if (!::google::protobuf::internal::AllAreInitialized(this_._internal_values()))
    return false;
  return true;
}

void Tile_Layer::InternalSwap(Tile_Layer* PROTOBUF_RESTRICT other) {
  using std::swap;
  _impl_._extensions_.InternalSwap(&other->_impl_._extensions_);
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.features_.InternalSwap(&other->_impl_.features_);
  _impl_.keys_.InternalSwap(&other->_impl_.keys_);
  _impl_.values_.InternalSwap(&other->_impl_.values_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.version_)
      + sizeof(Tile_Layer::_impl_.version_)
      - PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.extent_)>(
          reinterpret_cast<char*>(&_impl_.extent_),
          reinterpret_cast<char*>(&other->_impl_.extent_));
}

::google::protobuf::Metadata Tile_Layer::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Tile::_Internal {
 public:
};

Tile::Tile(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:vector_tile.Tile)
}
inline PROTOBUF_NDEBUG_INLINE Tile::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::vector_tile::Tile& from_msg)
      : _extensions_{visibility, arena},
        layers_{visibility, arena, from.layers_},
        _cached_size_{0} {}

Tile::Tile(
    ::google::protobuf::Arena* arena,
    const Tile& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Tile* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_._extensions_.MergeFrom(this, from._impl_._extensions_);

  // @@protoc_insertion_point(copy_constructor:vector_tile.Tile)
}
inline PROTOBUF_NDEBUG_INLINE Tile::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _extensions_{visibility, arena},
        layers_{visibility, arena},
        _cached_size_{0} {}

inline void Tile::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Tile::~Tile() {
  // @@protoc_insertion_point(destructor:vector_tile.Tile)
  SharedDtor(*this);
}
inline void Tile::SharedDtor(MessageLite& self) {
  Tile& this_ = static_cast<Tile&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* Tile::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Tile(arena);
}
constexpr auto Tile::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Tile, _impl_._extensions_) +
          decltype(Tile::_impl_._extensions_)::InternalGetArenaOffset(
              ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(Tile, _impl_.layers_) +
          decltype(Tile::_impl_.layers_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(Tile), alignof(Tile), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Tile::PlacementNew_,
                                 sizeof(Tile),
                                 alignof(Tile));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Tile::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Tile_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        Tile::IsInitializedImpl,
        &Tile::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Tile>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Tile::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Tile>(), &Tile::ByteSizeLong,
            &Tile::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Tile, _impl_._cached_size_),
        false,
    },
    &Tile::kDescriptorMethods,
    &descriptor_table_vector_5ftile_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Tile::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> Tile::_table_ = {
  {
    0,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(Tile, _impl_._extensions_),
    3, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967291,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::vector_tile::Tile>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .vector_tile.Tile.Layer layers = 3;
    {::_pbi::TcParser::FastMtR1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(Tile, _impl_.layers_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .vector_tile.Tile.Layer layers = 3;
    {PROTOBUF_FIELD_OFFSET(Tile, _impl_.layers_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::vector_tile::Tile_Layer>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void Tile::Clear() {
// @@protoc_insertion_point(message_clear_start:vector_tile.Tile)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_._extensions_.Clear();
  _impl_.layers_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Tile::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Tile& this_ = static_cast<const Tile&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Tile::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Tile& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:vector_tile.Tile)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .vector_tile.Tile.Layer layers = 3;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_layers_size());
               i < n; i++) {
            const auto& repfield = this_._internal_layers().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    3, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          // Extension range [16, 8192)
          target = this_._impl_._extensions_._InternalSerialize(
              internal_default_instance(), 16, 8192, target, stream);
          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:vector_tile.Tile)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Tile::ByteSizeLong(const MessageLite& base) {
          const Tile& this_ = static_cast<const Tile&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Tile::ByteSizeLong() const {
          const Tile& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:vector_tile.Tile)
          ::size_t total_size = 0;
          total_size += this_._impl_._extensions_.ByteSize();

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .vector_tile.Tile.Layer layers = 3;
            {
              total_size += 1UL * this_._internal_layers_size();
              for (const auto& msg : this_._internal_layers()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Tile::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Tile*>(&to_msg);
  auto& from = static_cast<const Tile&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:vector_tile.Tile)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_layers()->MergeFrom(
      from._internal_layers());
  _this->_impl_._extensions_.MergeFrom(internal_default_instance(), from._impl_._extensions_);
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Tile::CopyFrom(const Tile& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:vector_tile.Tile)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Tile::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const Tile&>(msg);
  if (!this_._impl_._extensions_.IsInitialized(
          internal_default_instance())) {
    return false;
  }
  if (!::google::protobuf::internal::AllAreInitialized(this_._internal_layers()))
    return false;
  return true;
}

void Tile::InternalSwap(Tile* PROTOBUF_RESTRICT other) {
  using std::swap;
  _impl_._extensions_.InternalSwap(&other->_impl_._extensions_);
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.layers_.InternalSwap(&other->_impl_.layers_);
}

::google::protobuf::Metadata Tile::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace vector_tile
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_vector_5ftile_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
