// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vector_tile.proto
// Protobuf C++ Version: 6.33.4

#include "vector_tile.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace vector_tile {

inline constexpr Tile_Value::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        string_value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        double_value_{0},
        int_value_{::int64_t{0}},
        float_value_{0},
        bool_value_{false},
        uint_value_{::uint64_t{0u}},
        sint_value_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR Tile_Value::Tile_Value(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(Tile_Value_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct Tile_ValueDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Tile_ValueDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Tile_ValueDefaultTypeInternal() {}
  union {
    Tile_Value _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Tile_ValueDefaultTypeInternal _Tile_Value_default_instance_;

inline constexpr Tile_Feature::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        tags_{},
        _tags_cached_byte_size_{0},
        geometry_{},
        _geometry_cached_byte_size_{0},
        id_{::uint64_t{0u}},
        type_{static_cast< ::vector_tile::Tile_GeomType >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR Tile_Feature::Tile_Feature(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(Tile_Feature_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct Tile_FeatureDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Tile_FeatureDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Tile_FeatureDefaultTypeInternal() {}
  union {
    Tile_Feature _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Tile_FeatureDefaultTypeInternal _Tile_Feature_default_instance_;

inline constexpr Tile_Layer::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        features_{},
        keys_{},
        values_{},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        extent_{4096u},
        version_{1u} {}

template <typename>
PROTOBUF_CONSTEXPR Tile_Layer::Tile_Layer(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(Tile_Layer_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct Tile_LayerDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Tile_LayerDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Tile_LayerDefaultTypeInternal() {}
  union {
    Tile_Layer _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Tile_LayerDefaultTypeInternal _Tile_Layer_default_instance_;

inline constexpr Tile::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        layers_{} {}

template <typename>
PROTOBUF_CONSTEXPR Tile::Tile(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(Tile_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TileDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TileDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TileDefaultTypeInternal() {}
  union {
    Tile _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TileDefaultTypeInternal _Tile_default_instance_;
}  // namespace vector_tile
namespace vector_tile {
PROTOBUF_CONSTINIT const uint32_t Tile_GeomType_internal_data_[] = {
    262144u, 0u, };
static ::google::protobuf::internal::ExplicitlyConstructed<::std::string>
    Tile_GeomType_strings[4] = {};

static const char Tile_GeomType_names[] = {
    "LINESTRING"
    "POINT"
    "POLYGON"
    "UNKNOWN"
};

static const ::google::protobuf::internal::EnumEntry Tile_GeomType_entries[] = {
    {{&Tile_GeomType_names[0], 10}, 2},
    {{&Tile_GeomType_names[10], 5}, 1},
    {{&Tile_GeomType_names[15], 7}, 3},
    {{&Tile_GeomType_names[22], 7}, 0},
};

static const int Tile_GeomType_entries_by_number[] = {
    3,  // 0 -> UNKNOWN
    1,  // 1 -> POINT
    0,  // 2 -> LINESTRING
    2,  // 3 -> POLYGON
};

const ::std::string& Tile_GeomType_Name(Tile_GeomType value) {
  static const bool kDummy = ::google::protobuf::internal::InitializeEnumStrings(
      Tile_GeomType_entries, Tile_GeomType_entries_by_number, 4,
      Tile_GeomType_strings);
  (void)kDummy;

  int idx = ::google::protobuf::internal::LookUpEnumName(Tile_GeomType_entries,
                                  Tile_GeomType_entries_by_number,
                                  4, value);
  return idx == -1 ? ::google::protobuf::internal::GetEmptyString() : Tile_GeomType_strings[idx].get();
}

bool Tile_GeomType_Parse(::absl::string_view name, Tile_GeomType* PROTOBUF_NONNULL value) {
  int int_value;
  bool success = ::google::protobuf::internal::LookUpEnumValue(
      Tile_GeomType_entries, 4, name, &int_value);
  if (success) {
    *value = static_cast<Tile_GeomType>(int_value);
  }
  return success;
}
// ===================================================================

class Tile_Value::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Tile_Value>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_._has_bits_);
};

Tile_Value::Tile_Value(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, Tile_Value_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:vector_tile.Tile.Value)
}
PROTOBUF_NDEBUG_INLINE Tile_Value::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::vector_tile::Tile_Value& from_msg)
      : _extensions_{visibility, arena},
        _has_bits_{from._has_bits_},
        _cached_size_{0},
        string_value_(arena, from.string_value_) {}

Tile_Value::Tile_Value(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Tile_Value& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, Tile_Value_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Tile_Value* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_._extensions_.MergeFrom(this, from._impl_._extensions_);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, double_value_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, double_value_),
           offsetof(Impl_, sint_value_) -
               offsetof(Impl_, double_value_) +
               sizeof(Impl_::sint_value_));

  // @@protoc_insertion_point(copy_constructor:vector_tile.Tile.Value)
}
PROTOBUF_NDEBUG_INLINE Tile_Value::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _extensions_{visibility, arena},
        _cached_size_{0},
        string_value_(arena) {}

inline void Tile_Value::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, double_value_),
           0,
           offsetof(Impl_, sint_value_) -
               offsetof(Impl_, double_value_) +
               sizeof(Impl_::sint_value_));
}
Tile_Value::~Tile_Value() {
  // @@protoc_insertion_point(destructor:vector_tile.Tile.Value)
  SharedDtor(*this);
}
inline void Tile_Value::SharedDtor(MessageLite& self) {
  Tile_Value& this_ = static_cast<Tile_Value&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.string_value_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Tile_Value::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Tile_Value(arena);
}
constexpr auto Tile_Value::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_._extensions_) +
          decltype(Tile_Value::_impl_._extensions_)::InternalGetArenaOffset(
              ::google::protobuf::MessageLite::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(Tile_Value), alignof(Tile_Value), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Tile_Value::PlacementNew_,
                                 sizeof(Tile_Value),
                                 alignof(Tile_Value));
  }
}
constexpr auto Tile_Value::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<23>{
      {
          &_Tile_Value_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          Tile_Value::IsInitializedImpl,
          &Tile_Value::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<Tile_Value>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Tile_Value::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<Tile_Value>(), &Tile_Value::ByteSizeLong,
              &Tile_Value::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_._cached_size_),
          true,
      },
      "vector_tile.Tile.Value",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<23> Tile_Value_class_data_ =
    Tile_Value::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Tile_Value::GetClassData() const {
  return Tile_Value_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 0, 0, 2>
Tile_Value::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_._extensions_),
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Tile_Value_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::vector_tile::Tile_Value>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional string string_value = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.string_value_)}},
    // optional float float_value = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 3, 0,
      PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.float_value_)}},
    // optional double double_value = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 1, 0,
      PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.double_value_)}},
    // optional int64 int_value = 4;
    {::_pbi::TcParser::FastV64S1,
     {32, 2, 0,
      PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.int_value_)}},
    // optional uint64 uint_value = 5;
    {::_pbi::TcParser::FastV64S1,
     {40, 5, 0,
      PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.uint_value_)}},
    // optional sint64 sint_value = 6;
    {::_pbi::TcParser::FastZ64S1,
     {48, 6, 0,
      PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.sint_value_)}},
    // optional bool bool_value = 7;
    {::_pbi::TcParser::FastV8S1,
     {56, 4, 0,
      PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.bool_value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string string_value = 1;
    {PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.string_value_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional float float_value = 2;
    {PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.float_value_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional double double_value = 3;
    {PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.double_value_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // optional int64 int_value = 4;
    {PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.int_value_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional uint64 uint_value = 5;
    {PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.uint_value_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // optional sint64 sint_value = 6;
    {PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.sint_value_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kSInt64)},
    // optional bool bool_value = 7;
    {PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.bool_value_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void Tile_Value::Clear() {
// @@protoc_insertion_point(message_clear_start:vector_tile.Tile.Value)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_._extensions_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.string_value_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000007eU)) {
    ::memset(&_impl_.double_value_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.sint_value_) -
        reinterpret_cast<char*>(&_impl_.double_value_)) + sizeof(_impl_.sint_value_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Tile_Value::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Tile_Value& this_ = static_cast<const Tile_Value&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Tile_Value::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Tile_Value& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:vector_tile.Tile.Value)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional string string_value = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_string_value();
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // optional float float_value = 2;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        2, this_._internal_float_value(), target);
  }

  // optional double double_value = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        3, this_._internal_double_value(), target);
  }

  // optional int64 int_value = 4;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<4>(
            stream, this_._internal_int_value(), target);
  }

  // optional uint64 uint_value = 5;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        5, this_._internal_uint_value(), target);
  }

  // optional sint64 sint_value = 6;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt64ToArray(
        6, this_._internal_sint_value(), target);
  }

  // optional bool bool_value = 7;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        7, this_._internal_bool_value(), target);
  }

  // All extensions.
  target = this_._impl_._extensions_._InternalSerializeAll(&default_instance(),
                                                    target, stream);
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:vector_tile.Tile.Value)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Tile_Value::ByteSizeLong(const MessageLite& base) {
  const Tile_Value& this_ = static_cast<const Tile_Value&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Tile_Value::ByteSizeLong() const {
  const Tile_Value& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:vector_tile.Tile.Value)
  ::size_t total_size = 0;
  total_size += this_._impl_._extensions_.ByteSize();

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += static_cast<bool>(0x00000002U & cached_has_bits) * 9;
  total_size += static_cast<bool>(0x00000008U & cached_has_bits) * 5;
  total_size += static_cast<bool>(0x00000010U & cached_has_bits) * 2;
  if (BatchCheckHasBit(cached_has_bits, 0x00000065U)) {
    // optional string string_value = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_string_value());
    }
    // optional int64 int_value = 4;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this_._internal_int_value());
    }
    // optional uint64 uint_value = 5;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this_._internal_uint_value());
    }
    // optional sint64 sint_value = 6;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      total_size += ::_pbi::WireFormatLite::SInt64SizePlusOne(
          this_._internal_sint_value());
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void Tile_Value::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Tile_Value*>(&to_msg);
  auto& from = static_cast<const Tile_Value&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:vector_tile.Tile.Value)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_string_value(from._internal_string_value());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.double_value_ = from._impl_.double_value_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.int_value_ = from._impl_.int_value_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.float_value_ = from._impl_.float_value_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.bool_value_ = from._impl_.bool_value_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      _this->_impl_.uint_value_ = from._impl_.uint_value_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      _this->_impl_.sint_value_ = from._impl_.sint_value_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_impl_._extensions_.MergeFrom(&default_instance(),
                                from._impl_._extensions_);
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void Tile_Value::CopyFrom(const Tile_Value& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:vector_tile.Tile.Value)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Tile_Value::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const Tile_Value&>(msg);
  if (!this_._impl_._extensions_.IsInitialized(&default_instance())) {
    return false;
  }
  return true;
}

void Tile_Value::InternalSwap(Tile_Value* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _impl_._extensions_.InternalSwap(&other->_impl_._extensions_);
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.string_value_, &other->_impl_.string_value_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.sint_value_)
      + sizeof(Tile_Value::_impl_.sint_value_)
      - PROTOBUF_FIELD_OFFSET(Tile_Value, _impl_.double_value_)>(
          reinterpret_cast<char*>(&_impl_.double_value_),
          reinterpret_cast<char*>(&other->_impl_.double_value_));
}

// ===================================================================

class Tile_Feature::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Tile_Feature>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Tile_Feature, _impl_._has_bits_);
};

Tile_Feature::Tile_Feature(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, Tile_Feature_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:vector_tile.Tile.Feature)
}
PROTOBUF_NDEBUG_INLINE Tile_Feature::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::vector_tile::Tile_Feature& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        tags_{visibility, arena, from.tags_},
        _tags_cached_byte_size_{0},
        geometry_{visibility, arena, from.geometry_},
        _geometry_cached_byte_size_{0} {}

Tile_Feature::Tile_Feature(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Tile_Feature& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, Tile_Feature_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Tile_Feature* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, type_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::type_));

  // @@protoc_insertion_point(copy_constructor:vector_tile.Tile.Feature)
}
PROTOBUF_NDEBUG_INLINE Tile_Feature::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        tags_{visibility, arena},
        _tags_cached_byte_size_{0},
        geometry_{visibility, arena},
        _geometry_cached_byte_size_{0} {}

inline void Tile_Feature::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, type_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::type_));
}
Tile_Feature::~Tile_Feature() {
  // @@protoc_insertion_point(destructor:vector_tile.Tile.Feature)
  SharedDtor(*this);
}
inline void Tile_Feature::SharedDtor(MessageLite& self) {
  Tile_Feature& this_ = static_cast<Tile_Feature&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Tile_Feature::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Tile_Feature(arena);
}
constexpr auto Tile_Feature::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Tile_Feature, _impl_.tags_) +
          decltype(Tile_Feature::_impl_.tags_)::
              InternalGetArenaOffset(
                  ::google::protobuf::MessageLite::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(Tile_Feature, _impl_.geometry_) +
          decltype(Tile_Feature::_impl_.geometry_)::
              InternalGetArenaOffset(
                  ::google::protobuf::MessageLite::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(Tile_Feature), alignof(Tile_Feature), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Tile_Feature::PlacementNew_,
                                 sizeof(Tile_Feature),
                                 alignof(Tile_Feature));
  }
}
constexpr auto Tile_Feature::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<25>{
      {
          &_Tile_Feature_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Tile_Feature::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<Tile_Feature>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Tile_Feature::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<Tile_Feature>(), &Tile_Feature::ByteSizeLong,
              &Tile_Feature::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Tile_Feature, _impl_._cached_size_),
          true,
      },
      "vector_tile.Tile.Feature",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<25> Tile_Feature_class_data_ =
    Tile_Feature::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Tile_Feature::GetClassData() const {
  return Tile_Feature_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 0, 2>
Tile_Feature::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Tile_Feature, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Tile_Feature_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::vector_tile::Tile_Feature>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated uint32 geometry = 4 [packed = true];
    {::_pbi::TcParser::FastV32P1,
     {34, 1, 0,
      PROTOBUF_FIELD_OFFSET(Tile_Feature, _impl_.geometry_)}},
    // optional uint64 id = 1 [default = 0];
    {::_pbi::TcParser::FastV64S1,
     {8, 2, 0,
      PROTOBUF_FIELD_OFFSET(Tile_Feature, _impl_.id_)}},
    // repeated uint32 tags = 2 [packed = true];
    {::_pbi::TcParser::FastV32P1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(Tile_Feature, _impl_.tags_)}},
    // optional .vector_tile.Tile.GeomType type = 3 [default = UNKNOWN];
    {::_pbi::TcParser::FastEr0S1,
     {24, 3, 3,
      PROTOBUF_FIELD_OFFSET(Tile_Feature, _impl_.type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional uint64 id = 1 [default = 0];
    {PROTOBUF_FIELD_OFFSET(Tile_Feature, _impl_.id_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // repeated uint32 tags = 2 [packed = true];
    {PROTOBUF_FIELD_OFFSET(Tile_Feature, _impl_.tags_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt32)},
    // optional .vector_tile.Tile.GeomType type = 3 [default = UNKNOWN];
    {PROTOBUF_FIELD_OFFSET(Tile_Feature, _impl_.type_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
    // repeated uint32 geometry = 4 [packed = true];
    {PROTOBUF_FIELD_OFFSET(Tile_Feature, _impl_.geometry_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt32)},
  }},
  {{
      {0, 3},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void Tile_Feature::Clear() {
// @@protoc_insertion_point(message_clear_start:vector_tile.Tile.Feature)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.tags_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _impl_.geometry_.Clear();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000000cU)) {
    ::memset(&_impl_.id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.type_) -
        reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.type_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Tile_Feature::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Tile_Feature& this_ = static_cast<const Tile_Feature&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Tile_Feature::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Tile_Feature& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:vector_tile.Tile.Feature)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional uint64 id = 1 [default = 0];
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this_._internal_id(), target);
  }

  // repeated uint32 tags = 2 [packed = true];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    {
      int byte_size = this_._impl_._tags_cached_byte_size_.Get();
      if (byte_size > 0) {
        target = stream->WriteUInt32Packed(
            2, this_._internal_tags(), byte_size, target);
      }
    }
  }

  // optional .vector_tile.Tile.GeomType type = 3 [default = UNKNOWN];
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        3, this_._internal_type(), target);
  }

  // repeated uint32 geometry = 4 [packed = true];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
    {
      int byte_size = this_._impl_._geometry_cached_byte_size_.Get();
      if (byte_size > 0) {
        target = stream->WriteUInt32Packed(
            4, this_._internal_geometry(), byte_size, target);
      }
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:vector_tile.Tile.Feature)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Tile_Feature::ByteSizeLong(const MessageLite& base) {
  const Tile_Feature& this_ = static_cast<const Tile_Feature&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Tile_Feature::ByteSizeLong() const {
  const Tile_Feature& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:vector_tile.Tile.Feature)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // repeated uint32 tags = 2 [packed = true];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size +=
          ::_pbi::WireFormatLite::UInt32SizeWithPackedTagSize(
              this_._internal_tags(), 1,
              this_._impl_._tags_cached_byte_size_);
    }
    // repeated uint32 geometry = 4 [packed = true];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      total_size +=
          ::_pbi::WireFormatLite::UInt32SizeWithPackedTagSize(
              this_._internal_geometry(), 1,
              this_._impl_._geometry_cached_byte_size_);
    }
    // optional uint64 id = 1 [default = 0];
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this_._internal_id());
    }
    // optional .vector_tile.Tile.GeomType type = 3 [default = UNKNOWN];
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void Tile_Feature::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Tile_Feature*>(&to_msg);
  auto& from = static_cast<const Tile_Feature&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:vector_tile.Tile.Feature)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_tags()->MergeFrom(from._internal_tags());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_geometry()->MergeFrom(from._internal_geometry());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.id_ = from._impl_.id_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.type_ = from._impl_.type_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void Tile_Feature::CopyFrom(const Tile_Feature& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:vector_tile.Tile.Feature)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Tile_Feature::InternalSwap(Tile_Feature* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.tags_.InternalSwap(&other->_impl_.tags_);
  _impl_.geometry_.InternalSwap(&other->_impl_.geometry_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Tile_Feature, _impl_.type_)
      + sizeof(Tile_Feature::_impl_.type_)
      - PROTOBUF_FIELD_OFFSET(Tile_Feature, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

// ===================================================================

class Tile_Layer::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Tile_Layer>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000028) ^ 0x00000028) != 0;
  }
};

Tile_Layer::Tile_Layer(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, Tile_Layer_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:vector_tile.Tile.Layer)
}
PROTOBUF_NDEBUG_INLINE Tile_Layer::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::vector_tile::Tile_Layer& from_msg)
      : _extensions_{visibility, arena},
        _has_bits_{from._has_bits_},
        _cached_size_{0},
        features_{visibility, arena, from.features_},
        keys_{visibility, arena, from.keys_},
        values_{visibility, arena, from.values_},
        name_(arena, from.name_) {}

Tile_Layer::Tile_Layer(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Tile_Layer& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, Tile_Layer_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Tile_Layer* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_._extensions_.MergeFrom(this, from._impl_._extensions_);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, extent_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, extent_),
           offsetof(Impl_, version_) -
               offsetof(Impl_, extent_) +
               sizeof(Impl_::version_));

  // @@protoc_insertion_point(copy_constructor:vector_tile.Tile.Layer)
}
PROTOBUF_NDEBUG_INLINE Tile_Layer::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _extensions_{visibility, arena},
        _cached_size_{0},
        features_{visibility, arena},
        keys_{visibility, arena},
        values_{visibility, arena},
        name_(arena),
        extent_{4096u},
        version_{1u} {}

inline void Tile_Layer::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Tile_Layer::~Tile_Layer() {
  // @@protoc_insertion_point(destructor:vector_tile.Tile.Layer)
  SharedDtor(*this);
}
inline void Tile_Layer::SharedDtor(MessageLite& self) {
  Tile_Layer& this_ = static_cast<Tile_Layer&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Tile_Layer::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Tile_Layer(arena);
}
constexpr auto Tile_Layer::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_._extensions_) +
          decltype(Tile_Layer::_impl_._extensions_)::InternalGetArenaOffset(
              ::google::protobuf::MessageLite::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.features_) +
          decltype(Tile_Layer::_impl_.features_)::
              InternalGetArenaOffset(
                  ::google::protobuf::MessageLite::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.keys_) +
          decltype(Tile_Layer::_impl_.keys_)::
              InternalGetArenaOffset(
                  ::google::protobuf::MessageLite::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.values_) +
          decltype(Tile_Layer::_impl_.values_)::
              InternalGetArenaOffset(
                  ::google::protobuf::MessageLite::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(Tile_Layer), alignof(Tile_Layer), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Tile_Layer::PlacementNew_,
                                 sizeof(Tile_Layer),
                                 alignof(Tile_Layer));
  }
}
constexpr auto Tile_Layer::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<23>{
      {
          &_Tile_Layer_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          Tile_Layer::IsInitializedImpl,
          &Tile_Layer::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<Tile_Layer>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Tile_Layer::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<Tile_Layer>(), &Tile_Layer::ByteSizeLong,
              &Tile_Layer::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_._cached_size_),
          true,
      },
      "vector_tile.Tile.Layer",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<23> Tile_Layer_class_data_ =
    Tile_Layer::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Tile_Layer::GetClassData() const {
  return Tile_Layer_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 2, 0, 2>
Tile_Layer::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_._extensions_),
    15, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294950880,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Tile_Layer_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::vector_tile::Tile_Layer>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // required string name = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 3, 0,
      PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.name_)}},
    // repeated .vector_tile.Tile.Feature features = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.features_)}},
    // repeated string keys = 3;
    {::_pbi::TcParser::FastBR1,
     {26, 1, 0,
      PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.keys_)}},
    // repeated .vector_tile.Tile.Value values = 4;
    {::_pbi::TcParser::FastMtR1,
     {34, 2, 1,
      PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.values_)}},
    // optional uint32 extent = 5 [default = 4096];
    {::_pbi::TcParser::FastV32S1,
     {40, 4, 0,
      PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.extent_)}},
    {::_pbi::TcParser::MiniParse, {}},
    // required uint32 version = 15 [default = 1];
    {::_pbi::TcParser::FastV32S1,
     {120, 5, 0,
      PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.version_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required string name = 1;
    {PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.name_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // repeated .vector_tile.Tile.Feature features = 2;
    {PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.features_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated string keys = 3;
    {PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.keys_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kBytes | ::_fl::kRepSString)},
    // repeated .vector_tile.Tile.Value values = 4;
    {PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.values_), _Internal::kHasBitsOffset + 2, 1, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional uint32 extent = 5 [default = 4096];
    {PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.extent_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // required uint32 version = 15 [default = 1];
    {PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.version_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::vector_tile::Tile_Feature>()},
      {::_pbi::TcParser::GetTable<::vector_tile::Tile_Value>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void Tile_Layer::Clear() {
// @@protoc_insertion_point(message_clear_start:vector_tile.Tile.Layer)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_._extensions_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.features_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _impl_.keys_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
      _impl_.values_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _impl_.name_.ClearNonDefaultToEmpty();
    }
    _impl_.extent_ = 4096u;
    _impl_.version_ = 1u;
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Tile_Layer::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Tile_Layer& this_ = static_cast<const Tile_Layer&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Tile_Layer::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Tile_Layer& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:vector_tile.Tile.Layer)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // required string name = 1;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    const ::std::string& _s = this_._internal_name();
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // repeated .vector_tile.Tile.Feature features = 2;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_features_size());
         i < n; i++) {
      const auto& repfield = this_._internal_features().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              2, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // repeated string keys = 3;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
    for (int i = 0, n = this_._internal_keys_size(); i < n; ++i) {
      const auto& s = this_._internal_keys().Get(i);
      target = stream->WriteString(3, s, target);
    }
  }

  // repeated .vector_tile.Tile.Value values = 4;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_values_size());
         i < n; i++) {
      const auto& repfield = this_._internal_values().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              4, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // optional uint32 extent = 5 [default = 4096];
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        5, this_._internal_extent(), target);
  }

  // required uint32 version = 15 [default = 1];
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        15, this_._internal_version(), target);
  }

  // All extensions.
  target = this_._impl_._extensions_._InternalSerializeAll(&default_instance(),
                                                    target, stream);
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:vector_tile.Tile.Layer)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Tile_Layer::ByteSizeLong(const MessageLite& base) {
  const Tile_Layer& this_ = static_cast<const Tile_Layer&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Tile_Layer::ByteSizeLong() const {
  const Tile_Layer& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:vector_tile.Tile.Layer)
  ::size_t total_size = 0;
  total_size += this_._impl_._extensions_.ByteSize();

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // repeated .vector_tile.Tile.Feature features = 2;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_features_size();
      for (const auto& msg : this_._internal_features()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // repeated string keys = 3;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_keys().size());
      for (int i = 0, n = this_._internal_keys().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            this_._internal_keys().Get(i));
      }
    }
    // repeated .vector_tile.Tile.Value values = 4;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
      total_size += 1UL * this_._internal_values_size();
      for (const auto& msg : this_._internal_values()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
   {
    // required string name = 1;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_name());
    }
  }
   {
    // optional uint32 extent = 5 [default = 4096];
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_extent());
    }
  }
   {
    // required uint32 version = 15 [default = 1];
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_version());
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void Tile_Layer::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Tile_Layer*>(&to_msg);
  auto& from = static_cast<const Tile_Layer&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:vector_tile.Tile.Layer)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_features()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_features());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_keys()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_keys());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
      _this->_internal_mutable_values()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_values());
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_internal_set_name(from._internal_name());
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.extent_ = from._impl_.extent_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      _this->_impl_.version_ = from._impl_.version_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_impl_._extensions_.MergeFrom(&default_instance(),
                                from._impl_._extensions_);
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void Tile_Layer::CopyFrom(const Tile_Layer& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:vector_tile.Tile.Layer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Tile_Layer::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const Tile_Layer&>(msg);
  if (!this_._impl_._extensions_.IsInitialized(&default_instance())) {
    return false;
  }
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  if (!::google::protobuf::internal::AllAreInitialized(this_._internal_values()))
    return false;
  return true;
}

void Tile_Layer::InternalSwap(Tile_Layer* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _impl_._extensions_.InternalSwap(&other->_impl_._extensions_);
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.features_.InternalSwap(&other->_impl_.features_);
  _impl_.keys_.InternalSwap(&other->_impl_.keys_);
  _impl_.values_.InternalSwap(&other->_impl_.values_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.version_)
      + sizeof(Tile_Layer::_impl_.version_)
      - PROTOBUF_FIELD_OFFSET(Tile_Layer, _impl_.extent_)>(
          reinterpret_cast<char*>(&_impl_.extent_),
          reinterpret_cast<char*>(&other->_impl_.extent_));
}

// ===================================================================

class Tile::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Tile>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Tile, _impl_._has_bits_);
};

Tile::Tile(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, Tile_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:vector_tile.Tile)
}
PROTOBUF_NDEBUG_INLINE Tile::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::vector_tile::Tile& from_msg)
      : _extensions_{visibility, arena},
        _has_bits_{from._has_bits_},
        _cached_size_{0},
        layers_{visibility, arena, from.layers_} {}

Tile::Tile(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Tile& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, Tile_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Tile* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_._extensions_.MergeFrom(this, from._impl_._extensions_);

  // @@protoc_insertion_point(copy_constructor:vector_tile.Tile)
}
PROTOBUF_NDEBUG_INLINE Tile::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _extensions_{visibility, arena},
        _cached_size_{0},
        layers_{visibility, arena} {}

inline void Tile::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Tile::~Tile() {
  // @@protoc_insertion_point(destructor:vector_tile.Tile)
  SharedDtor(*this);
}
inline void Tile::SharedDtor(MessageLite& self) {
  Tile& this_ = static_cast<Tile&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Tile::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Tile(arena);
}
constexpr auto Tile::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Tile, _impl_._extensions_) +
          decltype(Tile::_impl_._extensions_)::InternalGetArenaOffset(
              ::google::protobuf::MessageLite::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(Tile, _impl_.layers_) +
          decltype(Tile::_impl_.layers_)::
              InternalGetArenaOffset(
                  ::google::protobuf::MessageLite::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(Tile), alignof(Tile), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Tile::PlacementNew_,
                                 sizeof(Tile),
                                 alignof(Tile));
  }
}
constexpr auto Tile::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<17>{
      {
          &_Tile_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          Tile::IsInitializedImpl,
          &Tile::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<Tile>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Tile::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<Tile>(), &Tile::ByteSizeLong,
              &Tile::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Tile, _impl_._cached_size_),
          true,
      },
      "vector_tile.Tile",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<17> Tile_class_data_ =
    Tile::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Tile::GetClassData() const {
  return Tile_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
Tile::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Tile, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(Tile, _impl_._extensions_),
    3, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967291,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Tile_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::vector_tile::Tile>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .vector_tile.Tile.Layer layers = 3;
    {::_pbi::TcParser::FastMtR1,
     {26, 0, 0,
      PROTOBUF_FIELD_OFFSET(Tile, _impl_.layers_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .vector_tile.Tile.Layer layers = 3;
    {PROTOBUF_FIELD_OFFSET(Tile, _impl_.layers_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::vector_tile::Tile_Layer>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void Tile::Clear() {
// @@protoc_insertion_point(message_clear_start:vector_tile.Tile)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_._extensions_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.layers_.Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Tile::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Tile& this_ = static_cast<const Tile&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Tile::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Tile& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:vector_tile.Tile)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated .vector_tile.Tile.Layer layers = 3;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_layers_size());
         i < n; i++) {
      const auto& repfield = this_._internal_layers().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              3, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // All extensions.
  target = this_._impl_._extensions_._InternalSerializeAll(&default_instance(),
                                                    target, stream);
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:vector_tile.Tile)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Tile::ByteSizeLong(const MessageLite& base) {
  const Tile& this_ = static_cast<const Tile&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Tile::ByteSizeLong() const {
  const Tile& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:vector_tile.Tile)
  ::size_t total_size = 0;
  total_size += this_._impl_._extensions_.ByteSize();

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .vector_tile.Tile.Layer layers = 3;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_layers_size();
      for (const auto& msg : this_._internal_layers()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void Tile::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Tile*>(&to_msg);
  auto& from = static_cast<const Tile&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:vector_tile.Tile)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _this->_internal_mutable_layers()->InternalMergeFromWithArena(
        ::google::protobuf::MessageLite::internal_visibility(), arena,
        from._internal_layers());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_impl_._extensions_.MergeFrom(&default_instance(),
                                from._impl_._extensions_);
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void Tile::CopyFrom(const Tile& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:vector_tile.Tile)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Tile::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const Tile&>(msg);
  if (!this_._impl_._extensions_.IsInitialized(&default_instance())) {
    return false;
  }
  if (!::google::protobuf::internal::AllAreInitialized(this_._internal_layers()))
    return false;
  return true;
}

void Tile::InternalSwap(Tile* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _impl_._extensions_.InternalSwap(&other->_impl_._extensions_);
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.layers_.InternalSwap(&other->_impl_.layers_);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace vector_tile
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
